boardcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('boards/', views.boards_index, name='index'),
    path('boards/<int:board_id>/', views.boards_detail, name='detail'),
    path('boards/create/', views.BoardCreate.as_view(), name ='boards_create'),
    path('boards/<int:pk>/update/', views.BoardUpdate.as_view(), name='boards_update'),
    path('boards/<int:pk>/delete/', views.BoardDelete.as_view(), name='boards_delete'),
    path('boards/<int:board_id>/add_tuning/', views.add_tuning, name='add_tuning'),
    path('boards/<int:board_id>/assoc_binding/<int:binding_id>/', views.assoc_binding, name='assoc_binding'),
    path('boards/<int:board_id>/add_photo/', views.add_photo, name='add_photo'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
# models below.

class Binding(models.Model):
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    color= models.CharField(max_length=100)
    def __str__(self):
        return self.model
    def get_absolute_url(self):
        return reverse('binding_detail', kwargs={'pk': self.pk})

class Board(models.Model):
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    condition = models.CharField(max_length=300)
    age = models.IntegerField()
    bindings = models.ManyToManyField(Binding)

    def __str__(self):
        return self.brand
        
    def get_absolute_url(self):
        return reverse('detail', kwargs={'board_id': self.id})

PACKAGES = (
    ('S', "Minor Tune Up"),
    ('M', "Moderate Tune Up"),
    ('F','Full Tune Up'),
)
class Tuning(models.Model):
    date = models.DateField('Tuning Date')
    package = models.CharField(
        max_length=1,
            choices=PACKAGES,
            default=PACKAGES[0][0]  
        )
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
   
    def __str__(self):
        return f"{self.get_package_display()} on {self.date}"
    class Meta:
        ordering = ['-date']
        
class Photo(models.Model):
    url = models.CharField(max_length=200)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for board_id: {self.board_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Tuning

class TuningForm(ModelForm):
    class Meta:
        model = Tuning
        fields = ['date','package']
        

main_app/views.py
from django.shortcuts import redirect, render, redirect
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Binding, Board
from .forms import TuningForm
import uuid
import boto3
from .models import Board, Binding, Photo

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'catcollector1'

class BoardCreate(CreateView):
  model = Board
  fields = '__all__'

class BoardUpdate(UpdateView):
  model = Board
  # Let's disallow the renaming of a cat by excluding the name field!
  fields = '__all__'

class BoardDelete(DeleteView):
  model = Board
  success_url = '/boards/'


# Create your views here.
def home(request):
  return HttpResponse('<h1>Hello</h1>')

def about(request):
    return render (request, 'about.html')

  
def boards_index(request):
  boards = Board.objects.all()
  return render(request, 'boards/index.html',{'boards':boards})

def boards_detail(request, board_id):
  board = Board.objects.get(id=board_id)
  bindings_board_doesnt_have = Binding.objects.exclude(board = board.bindings.all().values_list('id'))
  tuning_form = TuningForm()
  return render(request, 'boards/detail.html', {'board': board, 'tuning_form': tuning_form})

def add_tuning(request, board_id):
  form = TuningForm(request.POST)
  if form.is_valid():
    new_tuning = form.save(commit=False)
    new_tuning.board_id = board_id 
    new_tuning.save()
  return redirect('detail', board_id=board_id)

def assoc_binding(request, boards_id, binding_id):
  Board.objects.get(id=boards_id).binding.add(binding_id)

def add_photo(request, board_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            Photo.objects.create(url=url, board_id=board_id)
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', board_id=board_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>BoardCollector</h1>
<hr />
<p>BUY, SELL, AND, EXPLORE BOARDS!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Board Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;BoardCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'boards_create' %}">Add A Board</a></li>
          <li><a href="/boards">View All My Boards</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2019 Cat Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/boards/detail.html
{% extends 'base.html' %}
{% block content %}
    
<h1>Board Details</h1>

<div class="row">
    <div class="col s6">
      <div class="card">
            <div class="card-content">
                <span class="card-title">{{ board.brand }}</span>
                <p>Model: {{ board.model }}</p>
                <p>Description: {{ board.description }} </p>
                {% if board.age > 0 %}
                <p>Age: {{ board.age }}</p>
                {% else %}
                <p>Not Yet Released</p>
                {% endif %}
            </div>
            <div class="card-action">
                <a href="{% url 'boards_update' board.id %}">Edit</a>
                <a href="{% url 'boards_delete' board.id %}">Delete</a>
            </div>
        </div>
    </div>
    <div class="col s6">
        <form action="{% url 'add_tuning' board.id %}" method="post">
            {% csrf_token %}
            {{ tuning_form.as_p }}
            <input  type="submit" class="btn" value="Add Tune Ups">
        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Tuning</th>
                </tr>
            </thead>
            <tbody>
                {% for tuning in board.tuning_set.all %}
                <tr>
                    <td>{{tuning.date}}</td>
                    <td>{{tuning.get_package_display}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ board.brand }} {{ board.model }}'s Bindings</h3>
    {% if board.bindings.count %}
      {% for binding in board.bindings.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ bindings.color }}">{{ bindings.color }}</span> {{ bindings.model }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Bindings:(</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Bindings</h3>
    {% if bindings.count %}
      {% for binding in binding.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ binding.color }}">{{ binding.color }}</span> {{ binding.model }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_binding' board.id binding.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{cat.name}} Already Has Available Bindings</h5>
    {% endif %}
  </div>
<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    const selectEl = document.getElementById('id_package');
    M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/boards/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Board List</h1>

{% for board in boards %}
  <div class="card">
    <a href="{% url 'detail' board.id %}">
    <div class="card-content">
      <span class="card-title">{{ board.model }}</span>
      <p>Brand: {{ board.brand }}</p>
      <p>Description: {{ board.description }}</p>
      {% if board.age > 0 %}
        <p>Age: {{ board.age }}</p>
      {% else %}
        <p>Age: coming soon</p>
      {% endif %}
    </div>
  </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/main_app/board_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Board</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' board.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/board_form.html
{% extends 'base.html' %}
{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Board</h1>
{% endif %}
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!" class="btn">
    </form>
{% endblock %}
    